@extends('admin.layouts.app')
@section('title', 'Locations')
@section('page_heading', 'Locations')
@section('content')
<section class="ma-page-heading"><div><p class="ma-eyebrow">Discovery Geography</p><h2>Locations</h2><p>Manage structured city, postal and coordinate data that Makers can use now and future radius-based discovery can query efficiently.</p></div><span class="ma-pill">{{ number_format($locations->total()) }} matching locations</span></section>
@if ($errors->any())<div class="ma-alert ma-alert--error" role="alert"><div><strong>Please correct the following.</strong><ul class="ma-error-list">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif
<div class="ma-detail-grid">
<section class="ma-panel"><div class="ma-panel__header"><div><p class="ma-eyebrow">Add Location</p><h3>New managed location</h3></div></div><form class="ma-form" method="POST" action="{{ route('admin.locations.store') }}">@csrf
<div class="ma-form-grid"><div class="ma-field"><label for="city">City</label><input id="city" name="city" value="{{ old('city') }}" maxlength="120" required></div><div class="ma-field"><label for="region">State / Region</label><input id="region" name="region" value="{{ old('region') }}" maxlength="120"></div></div>
<div class="ma-form-grid"><div class="ma-field"><label for="postal_code">ZIP / Postal code</label><input id="postal_code" name="postal_code" value="{{ old('postal_code') }}" maxlength="32"></div><div class="ma-field"><label for="country_code">Country code</label><input id="country_code" name="country_code" value="{{ old('country_code') }}" maxlength="2" minlength="2" placeholder="US" required><small class="ma-field__hint">ISO 3166-1 alpha-2, e.g. US, GB, PK.</small></div></div>
<div class="ma-form-grid"><div class="ma-field"><label for="latitude">Latitude</label><input id="latitude" name="latitude" type="number" step="0.0000001" min="-90" max="90" value="{{ old('latitude') }}"></div><div class="ma-field"><label for="longitude">Longitude</label><input id="longitude" name="longitude" type="number" step="0.0000001" min="-180" max="180" value="{{ old('longitude') }}"></div></div>
<div class="ma-field"><label for="sort_order">Sort order</label><input id="sort_order" name="sort_order" type="number" min="0" max="1000000" value="{{ old('sort_order', 0) }}" required></div><input type="hidden" name="is_active" value="0"><label class="ma-checkbox"><input name="is_active" type="checkbox" value="1" @checked((string) old('is_active', '1') === '1')><span>Active</span></label><div class="ma-form-actions"><button class="ma-button ma-button--primary" type="submit">Add Location</button></div></form></section>
<section class="ma-panel ma-panel--filters"><div class="ma-panel__header"><div><p class="ma-eyebrow">Find</p><h3>Filter locations</h3></div></div><form class="ma-form" method="GET" action="{{ route('admin.locations.index') }}"><div class="ma-field"><label for="search">Search</label><input id="search" name="search" type="search" value="{{ $filters['search'] ?? '' }}" placeholder="City, region or postal code"></div><div class="ma-field"><label for="filter_country_code">Country code</label><input id="filter_country_code" name="country_code" maxlength="2" value="{{ $filters['country_code'] ?? '' }}"></div><div class="ma-field"><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option><option value="active" @selected(($filters['status'] ?? '')==='active')>Active</option><option value="inactive" @selected(($filters['status'] ?? '')==='inactive')>Inactive</option></select></div><div class="ma-form-actions"><button class="ma-button ma-button--primary" type="submit">Apply filters</button><a class="ma-button ma-button--outline" href="{{ route('admin.locations.index') }}">Reset</a></div></form></section>
</div>
<section class="ma-panel"><div class="ma-panel__header"><div><p class="ma-eyebrow">Managed Geography</p><h3>Location directory</h3></div><span class="ma-panel__meta">20 per page</span></div>@if($locations->isEmpty())<div class="ma-empty-state"><span class="ma-empty-state__icon">◇</span><h4>No matching locations</h4><p>Add one or clear the filters.</p></div>@else<div class="ma-table-wrap"><table class="ma-table"><thead><tr><th>Location</th><th>Coordinates</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach($locations as $location)<tr><td data-label="Location"><strong>{{ $location->displayLabel() }}</strong></td><td data-label="Coordinates"><small>{{ $location->latitude !== null ? $location->latitude.', '.$location->longitude : 'Not set' }}</small></td><td data-label="Order">{{ $location->sort_order }}</td><td data-label="Status"><span class="ma-badge {{ $location->is_active ? 'ma-badge--success':'ma-badge--muted' }}">{{ $location->is_active ? 'Active':'Inactive' }}</span></td><td data-label="Actions"><div class="ma-form-actions"><a class="ma-button ma-button--outline" href="{{ route('admin.locations.edit',$location) }}">Edit</a><form method="POST" action="{{ route('admin.locations.toggle-status',$location) }}">@csrf @method('PATCH')<button class="ma-button ma-button--outline" type="submit">{{ $location->is_active ? 'Disable':'Enable' }}</button></form><form method="POST" action="{{ route('admin.locations.destroy',$location) }}" onsubmit="return confirm('Delete this location? Existing Maker links remain protected through soft deletion.');">@csrf @method('DELETE')<button class="ma-button ma-button--danger" type="submit">Delete</button></form></div></td></tr>@endforeach</tbody></table></div>@include('admin.partials.pagination',['paginator'=>$locations])@endif</section>
@endsection
